- type: job
  id: WardenHelper
  name: job-name-wardenHelper
  description: job-description-wardenHelper
  playTimeTracker: JobWardenHelper
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hrs
  startingGear: WardenHelperGear
  icon: "JobIconWardenHelper"
  supervisors: job-supervisors-hos
  weight: 5
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CanChokeGrab # Corvax-Next-Grab
      - type: Skills # Corvax-Next-Skills
        skills:
        - Shooting

- type: startingGear
  id: WardenHelperGear
  equipment:
    head: ClothingHeadHatWardenHelper
    eyes: ClothingEyesGlassesSecurity
    id: WardenHelperPDA
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
    pocket2: BookSpaceLaw
  storage:
    back:
    - Flash
    - MagazinePistol
    - ClothingNeckSecBadgeWardenHelper
