- type: entity
  id: BaseStation
  abstract: true
  components:
    - type: StationData

- type: entity
  id: BaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
    - type: StationCargoOrderDatabase
      orders:
        Cargo: [ ]
        Engineering: [ ]
        Medical: [ ]
        Science: [ ]
        Security: [ ]
        Service: [ ]
    - type: StationCargoBountyDatabase

- type: entity
  id: BaseStationJobsSpawning
  abstract: true
  components:
    - type: StationJobs
      availableJobs: {}
    - type: StationSpawning

- type: entity
  id: BaseStationRecords
  abstract: true
  components:
    - type: StationRecords

- type: entity
  id: BaseStationArrivals
  abstract: true
  components:
    - type: StationArrivals

- type: entity
  id: BaseStationGateway
  abstract: true
  components:
    - type: GatewayGenerator

- type: entity
  id: BaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/Shuttles/cargo.yml
    - type: GridSpawn
      groups:
        trade: !type:GridSpawnGroup
          addComponents:
            - type: ProtectedGrid
            - type: TradeStation
          paths:
            - /Maps/Shuttles/trading_outpost.yml
        mining: !type:GridSpawnGroup
          # Corvax-Next-Mining-Start
          hide: true
          nameGrid: true
          paths:
          - /Maps/Next/Shuttles/next_mining.yml
          # Corvax-Next-Mining-End
        # Spawn last
        ruins: !type:GridSpawnGroup
          hide: true
          nameGrid: true
          # Corvax-Next-Mining-Start
          minCount: 1
          maxCount: 1
          # Corvax-Next-Mining-End
          stationGrid: false
          paths:
          - /Maps/Ruins/abandoned_outpost.yml
          # Corvax-Mapping-Start
          - /Maps/Corvax/Ruins/corvax_accident.yml
          - /Maps/Corvax/Ruins/corvax_adventurer.yml
          - /Maps/Corvax/Ruins/corvax_aplink.yml
          - /Maps/Corvax/Ruins/corvax_battleship.yml
          - /Maps/Corvax/Ruins/corvax_gas_station.yml
          - /Maps/Corvax/Ruins/corvax_bss_unluck.yml
          - /Maps/Corvax/Ruins/corvax_hotel_trivago.yml
          - /Maps/Corvax/Ruins/corvax_kamikaze.yml
          - /Maps/Corvax/Ruins/corvax_ore.yml
          - /Maps/Corvax/Ruins/corvax_research_station.yml
          - /Maps/Corvax/Ruins/corvax_rnd_debris.yml
          - /Maps/Corvax/Ruins/corvax_sanctus.yml
          - /Maps/Corvax/Ruins/corvax_ussp_debris.yml
          - /Maps/Corvax/Ruins/corvax_ussp_asteroid.yml
          # Corvax-Mapping-End
          - /Maps/Ruins/wrecklaimer.yml
          - /Maps/Ruins/displaced_telescience.yml
#        vgroid: !type:DungeonSpawnGroup
#          minimumDistance: 400
#          maximumDistance: 450
#          nameDataset: NamesBorer
#          stationGrid: false
#          addComponents:
#          - type: Gravity
#            enabled: true
#            inherent: true
#          protos:
#          - VGRoid
#        # Corvax-Mapping-Start
#        mining: !type:GridSpawnGroup
#          paths:
#          - /Maps/Corvax/Shuttles/corvax_mining.yml
        # Corvax-Mapping-End

- type: entity
  id: BaseStationCentcomm
  abstract: true
  components:
    - type: StationCentcomm
      map: "/Maps/Corvax/corvax_centcomm.yml" # Corvax-Mapping

- type: entity
  id: BaseStationEvacuation
  abstract: true
  components:
    - type: StationEmergencyShuttle

- type: entity
  id: BaseStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: stationAlerts

- type: entity
  id: BaseStationExpeditions
  abstract: true
  components:
    - type: SalvageExpeditionData

- type: entity
  id: BaseStationMagnet
  abstract: true
  components:
    - type: SalvageMagnetData

- type: entity
  id: BaseStationSalvageJobs
  abstract: true
  components:
  - type: SalvageJobsData
    rankThresholds:
      0:
        title: salvage-job-rank-title-0
        bountyGroup: SalvageJobTier1
      3:
        title: salvage-job-rank-title-1
        bountyGroup: SalvageJobTier2
        unlockedMarket: SalvageJobReward2
      6:
        title: salvage-job-rank-title-2
        bountyGroup: SalvageJobTier3
        unlockedMarket: SalvageJobReward3
    maxRank:
      title: salvage-job-rank-title-MAX
      unlockedMarket: SalvageJobRewardMAX

- type: entity
  id: BaseStationSiliconLawCrewsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Crewsimov

- type: entity
  id: BaseStationNews
  abstract: true
  components:
    - type: StationNews

- type: entity
  id: BaseStationDeliveries
  abstract: true
  components:
  - type: CargoDeliveryData

- type: entity
  id: BaseStationAllEventsEligible
  abstract: true
  components:
    - type: StationEventEligible # For when someone makes this more granular in the future.
